### ISSUE TITLE
Random Issue

### ISSUE THREAD

**Issue by vipin1493** [Infineon/getstarted-optiga-trust-m#2]
I am not able to enable random number, it shows the error of 0202.

kindly send the steps to rectify the issue and generate the random number generation.

Thank you,

Regards,
Hitesh

**Comment by vipin1493** [comment]
Any comment on this ??

**Comment by pwiegele** [comment]
Hi vipin1493,

you can find the definition of the error [here](https://github.com/Infineon/optiga-trust-m/blob/fd610db43dee5cbc95189e0e63b4d1a194851d1a/optiga/include/optiga/common/optiga_lib_return_codes.h#L94).

This is a generic error which comes from the cmd module [here](https://github.com/Infineon/optiga-trust-m/blob/fd610db43dee5cbc95189e0e63b4d1a194851d1a/optiga/cmd/optiga_cmd.c).

Can you enable logging [here](https://github.com/Infineon/optiga-trust-m/blob/master/optiga/include/optiga/optiga_lib_config.h#L93) and post the log?

What happens if you request 8 bytes of data from the getrandom call?


BR Paul

**Comment by pwiegele** [comment]
@vipin1493 
Any update on this issue?
